### PR TITLE
Changes for joining an existing cluster

### PR DESCRIPTION
**Pull request by DEvil0000**
with this change transition a setup from single node to a joined cluster is possible

### CODE REVIEW

**Comment by dallinb** [comment]
@DEvil0000 & @tobias-tress, thank you for this PR.  I am super busy at the moment so it may have to wait until the weekend before I properly check this out and get it into a release.

**Review by dallinb — COMMENTED** [review]
Having the role handle a node joining a cluster is a great idea.  Just need to clarify how this would be used.  I am guessing that one would do something similar to the following:

```shell
ansible-playbook site.yml -i hosts --limit new_node \
  -e cassandra_join_cluster=true \
  -e cassandra_path=/data/cassandra
```

But I don't see what `cassandra_node_count` is adding to this as it is not referred to anywhere else?

Just asking so that I can document (and possibly add system tests) the new feature.

**Comment by DEvil0000** [comment]
Sorry, I missed some tasks in the branch - now it should be complete. 
`cassandra_node_count` is a fact - it tracks how many nodes are currently in the cluster.
Deleting data should only be done on the single node which should get joined to a cluster but not a running cluster.

**Comment by DEvil0000** [comment]
Not sure why it fails on the shell part. Did apply the pipefail thing since ansible-lint was sugesting it. see: https://github.com/ansible/ansible-lint/issues/497

Before that I had it like this:
```
shell: "nodetool status | awk '/^(U|D)(N|L|J|M)/{print $2}' | wc -l"
```

**Comment by dallinb** [comment]
OK, leave it with me for now.  It might be Monday before I get to look at this again but I think I get the idea of what is happening.  I also have to ensure that it works on all the supported platforms and is idempotent.  I'll merge your stuff onto a branch (so that you are credited) and put in a PR so you can see what I have done.

**Comment by dallinb** [comment]
I need to sort out #84 and #85 (in progress now) so that we can put some Molecule testing around this change.  I've taken a pull of this branch (to include your commits) and I am getting that working in the test environment.

My idea is to run the current tests which run against multiple nodes but they are running as single node clusters.  Then run a subsequent scenario to execute your code to merge the separate nodes into one cluster.

**Comment by DEvil0000** [comment]
Basically I agree but I think the second part (form a cluster/join a cluster) should be applied to some of the nodes early and for some later.
like having three nodes as single, form a cluster out of two and then join the last one.
This should cover all cases.

Edit:
it may make a difference if all nodes contain the same tables with some data so there should be some prefill when they are solo.

**Comment by dallinb** [comment]
I agree with your testing plan.  This change is going to be a bit of a pain.  It also reminds me of the workaround I had to do for [CASSANDRA-2356](https://issues.apache.org/jira/browse/CASSANDRA-2356) which was the packages for Debian would do an initial start up of Cassandra with default settings which meant you had to figure out a safe way to blow away the data so the node would join a cluster.  We also have the problem that `nodetool` can be an unreliable witness for one or more of these reasons:

- Checking the status from nodetool before the package is installed (seems obvious but worth noting).
- Checking the status from nodetool when the software is installed, but the service is not running (will cause an error because nodetool can't connect to a running service).
- Checking the status from nodetool, the service is running but is configured from default settings (this could be that the default port has been changed so needs to be specified on the command line or that authentication has been enabled in Cassandra).

It will be complex, but worthwhile to implement.

**Comment by dallinb** [comment]
Made an initial attempt at this with https://github.com/locp/ansible-role-cassandra/tree/feature/join_cluster (you can see the test transcript at https://travis-ci.com/github/locp/ansible-role-cassandra/builds/167528629).

1. We have four nodes (node0 - node3) in the initial run, node0 and node1 are in a two node cluster and node2 and node3 and in standalone clusters by themselves.
2. In the second test, node2 is joined to the cluster the larger cluster.
3. In the third test, node3 is joined to the main cluster.

I'm not sure if we're proving anything functionally by having this in three steps, so if you agree, I will merge steps 2 and 3 so that both of the standalone nodes (node2 and node3) will be created as standalone nodes in step 1, but will subsequently both be added to the main cluster at the same time.

**Comment by DEvil0000** [comment]
agree, and looks good.

Just as side note: ansible service module should work on all systems and actually uses systemd if there. debian however also has systemd since a good while. there is normally no need to differentiate.

**Pull request merged**
